### ISSUE TITLE
similar colors in PHPStorm

### ISSUE THREAD

**Issue by pr0grammr** [jasonhulbert/jetbrains-trash-panda-theme#1]
hey,

i really like the theme, but in PHPStorm the colors of variables, parameters, keywords and builtin functions are looking very similar. is there a way to bring more variations? (see screenshot)

in intellij like in the screenshot in the plugin preview, it looks more fancy

![Screenshot-20190925123701-706x658](https://user-images.githubusercontent.com/17650157/65593747-6f2d4300-df91-11e9-9a46-926ae45bcaa4.png)

**Comment by jasonhulbert** [comment]
@pr0grammr First of all, thanks for the feedback! So far I've been focused on the syntax for the stack that my team uses which is node and java (and frontend stuff) so thank you for pointing this out. I'll make adjustments for PHP in the next publish. Looks like some defaults need to replaced based on the screenshot you provided.

**Comment by jasonhulbert** [comment]
Since I was already preparing a publish, I went ahead and added these changes in. The update should get approved in the next couple of days and will be available to you.

<img width="1196" alt="Screen Shot 2019-09-26 at 12 44 46 PM" src="https://user-images.githubusercontent.com/1451375/65708387-7bca9d80-e05c-11e9-996f-8bc8cb08d95c.png">
