### ISSUE TITLE
Theme has different color scheme

### ISSUE THREAD

**Issue by IM-IgniteDEV** [jasonhulbert/jetbrains-trash-panda-theme#13]
My color scheme looks different than this one on preview 

![image](https://user-images.githubusercontent.com/31209154/180000539-e258d2c9-0cc3-4ed6-86b9-0014adcc9011.png)

**Comment by jasonhulbert** [comment]
Hey @IM-IgniteDEV - First, just want to point out that 2.0 of this plugin was published today and numerous updates/changes were made. Based on your screenshots, I'm assuming the issue you encountered is one of two things:
- You selected the "Editor -> Color Scheme" instead of "Appearance & Behavior -> Appearance -> Theme". The latter will set the theme for the entire UI as well as the editor where as the former will only set the editor theme.
- Or what you're pointing out is some missing syntax colors in java specifically. If so, you'll see many improvements in various languages by updating to 2.0.
