### ISSUE TITLE
in webstorm23.2.1 code edit upper right corner, detect code error number transparent   

### ISSUE THREAD

**Issue by scripted-C20** [jasonhulbert/jetbrains-trash-panda-theme#37]
![9c59e5c124527b2aa9681c82d46a6d7](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/36700965/bddb1dee-2867-4b14-9ad2-bbb4fb2144da)

**Comment by scripted-C20** [comment]
All themes do

**Comment by jasonhulbert** [comment]
We don't have settings that would specifically override the color of those editor buttons.

If you switched from a dark theme to a light theme without restarting your IDE, I would suggest trying a restart. These weird rendering artifacts happen often when switching between themes.

Otherwise, make sure that you haven't made any color scheme changes in your settings. If you have, you may want to consider restoring the defaults to avoid unexpected issues like this.
