### ISSUE TITLE
Moonlight, light, and high contrast themes missing after update in webstorm

### ISSUE THREAD

**Issue by aaron-lomba-zi** [jasonhulbert/jetbrains-trash-panda-theme#44]
<img width="321" alt="image" src="https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/72622051/2c33fd6e-e308-4d0a-b84d-259b9700eb3d">

I have not updated my other jetbrains IDEs

Plugin version: 1.6
Webstorm version: 2023.3.1

**Comment by aaron-lomba-zi** [comment]
Maybe it's the plugin version? 1.6 seems... wrong. But that's what I seen in the plugin marketplace

**Comment by jasonhulbert** [comment]
A couple of things to clarify here. 

The current version of the plugin is 2.0.6 (not 1.6). The IDE falls back to this very old 1.6 version when the plugin is not compatible with your version of IDE.

Secondly, there appears to be an ongoing issue in the latest product version (2023.3). The issue is causing theme files to not be resolved correctly - as far as I can tell. When switching the IDE theme in "Appearance", the corresponding "Color Scheme" in editor settings does not switch. **The IDE is failing to resolve the scheme .xml file path even though nothing has changed in this regard in the plugin source/configs.**

In my experience, JetBrains has a pattern of doing this. It's the latest occurrence of what seems like ignorance or lack of concern for how difficult it is to maintain a healthy, working plugin without constant attention. It seems like every release of their products causes mysterious compatibility issues for plugin authors. We're left digging through Gradle configs, Java compatibility tables, plugin build dependencies, package repository settings, test dependencies, etc. I can see that others have also reported this issue on YouTrack over the past week and, no surprise, JetBrains has yet to provide any guidance or a point of reference for those looking to understand and/or fix their broken themes.

**Comment by jasonhulbert** [comment]
https://youtrack.jetbrains.com/issue/IDEA-341505/Themes-not-applying-correctly-in-2023.3.1

**Comment by jasonhulbert** [comment]
Published 2.0.7 to the marketplace which should resolve this issue. Pending approval which usually takes a day or two.
