### ISSUE TITLE
The theme does not work with the new version of intellij

### ISSUE THREAD

**Issue by maurii9070** [jasonhulbert/jetbrains-trash-panda-theme#64]
When updating to a new version the themes stopped working
![image](https://github.com/user-attachments/assets/8a776ab1-fed4-49aa-9325-fb771b4a41bb)

**Comment by wstaud** [comment]
I can also verify. Seems to have fallen back to version 1.6. 

<img width="776" alt="Screenshot 2024-11-13 at 10 49 50 PM" src="https://github.com/user-attachments/assets/e474d751-35b6-47fb-b618-56b4fe4663ba">

**Comment by nemathew** [comment]
Ran into the same issue, tried to install the newest version from plugin homepage and got this error: 
![image](https://github.com/user-attachments/assets/de12db1a-a5c2-428d-ad01-5abaf7749903)

**Comment by mythron** [comment]
**For someone who wants to build it themselves:**

The theme runs fine on build 243 if you build it yourself.
You must change the version requirement in the `build.gradle` file: `untilBuild.set('243.*')`
You will also need java-jdk version 20 and python3 with ruamel_yaml package installed.

**Comment by jasonhulbert** [comment]
Just uploaded the 2.2.2 version for compatibility with latest major version. Should be available for update/download in the next day or 2 once approved.

**Comment by jasonhulbert** [comment]
I’m gonna use this issue for the purpose of pinning this topic (which comes up every major release).

First of all, just want to say thanks to everyone. This issue is annoying, I agree. I appreciate your patience and contributions.

The problem is that plugin authors used to be able to just mark a package as compatible “since version [x]”. Some time ago, it was strongly encouraged that plugins migrate to the gradle project structure and, in doing so, we were required to also mark packages with an “until version [x]”. That’s why when a new major version of jetbrains IDEs is released, the theme rolls all the way back to 1.6 - which was the last version that did not have a “until version” specified. At this point, there’s not much I can do to retroactively resolve this issue and will just have to try to publish an update as quickly as possible when new, major versions of IDEs are released.

🤷🏻
